### ISSUE TITLE
select2 4.0

### ISSUE THREAD

**Issue by NyroTheCat** [t0m/select2-bootstrap-css#63]
Hey fk/t0m,
select2 is in new 4.0 beta. Still not finished but i'm very exited if you will make an update to this. Select2 now supports a special theme option. May this becomes very handy ;)

Regards
Nyro

**Comment by kevin-brown** [comment]
Just to add onto this, I'm interested in seeing the work here be merged back into the main Select2 repository. Now that we have real theme support (and not the previous hacks that we worked with), it should be considerably easier to make Select2 fit it with the rest of Bootstrap.

I'd be willing to help if you are interested in contributing a Bootstrap theme to the main repository.

**Comment by flip111** [comment]
:+1:

**Comment by fk** [comment]
Hey all!

@NyroTheCat, thanks for letting me know – I was aware of the v4 branch and even snatched the "[Select2 custom data load](https://fk.github.io/select2-bootstrap-css/3.5.2.html)" demos code from that branch (kudos @kevin-brown! :)), but I totally missed the beta!

@kevin-brown, thanks for chiming in, showing interest for what has been going on over here and offering your help (_and_ for all your work maintaining and developing Select2!); I'm definitively interested, but can't make any promises right now (workload – I'm a bit "on the run" even right now :/) … _but_ for starters, I will take a look at the new Select2 and its theme support in the next few days.

**Comment by yanickrochon** [comment]
:+1:

**Comment by prophe05** [comment]
+1

**Comment by Knoxvillekm** [comment]
what's new?

**Comment by step307** [comment]
+1

**Comment by amccoll111** [comment]
+1

**Comment by ifthenelse** [comment]
+1

**Comment by Soullivaneuh** [comment]
+1

**Comment by LukaszKrawczyk** [comment]
:+1:

**Comment by fk** [comment]
Thanks for all your feedback folks!

I just checked out a new local branch and still have an hour to look into this tonight.
While this still isn't a promise that a "select2-v4-bootstrap3-css" will actually happen, it's start.

**Comment by fk** [comment]
I managed to implement the single Select2 styles yesterday (still a little rough around the edges) and hope to give the multiple Select2 styles a shot over the coming weekend.

@kevin-brown I saw that Select2 v4 does no longer copy the CSS-classes of the original `<select>` element to the generated dropdown and container elements.

While I have to say that I was a little annoyed by that when I first "got into" Select2, I found it to come in handy when working with Bootstraps "[Control sizing](http://getbootstrap.com/css/#forms-control-sizes)" classes which the current version of select2-bootstrap3.css [supports](https://fk.github.io/select2-bootstrap-css/master.html): Give the `<select>` that Select2 is initialized on an `.input-sm` would cause the class to be copied to the generated Select2 container where it could serve as a "CSS hook" to attach styles to handle the in- or decrease of font-size, border-radius, height, line-height and padding.

I briefly thought about using the `containerCssClass` option as a workaround to support "Control sizing" in the Bootstrap theme for Select2 v4 – only to find out that it is gone :-( – any ideas on how to make that work?

**Comment by fk** [comment]
I'm happy to report that the multiple Select2 styles are done – however styles generally are a bit too verbose for my liking right now and need a bit of refactoring, plus RTL support, tests for nested options, and cross-browser testing are still pending – and the problems described in my previous comments still remain.

I won't be able to do much during the coming week, but you can expect and update next weeked.
This is definitively happening. :heavy_check_mark:

**Comment by sdespont** [comment]
+1

**Comment by ryanbeymer** [comment]
Evening, 

@fk - I've been playing around with this as well for an hour or so and finding they switched a few things around as you referenced above. Anyway you could throw up your branch with the v4 changes on it?

**Comment by raistlinthewiz** [comment]
:thumbsup:

**Comment by kevin-brown** [comment]
It's good to here that some progress is being made (even if roadblocks exist), and it'd be awesome to see just what it looks like in a branch.

>  I saw that Select2 v4 does no longer copy the CSS-classes of the original `<select>` element to the generated dropdown and container elements.

Still figuring out how we are going to support all of the old CSS options (there were quite a few) without over complicating things by default. It may end up only in the full build, and I'm going to use the following ticket for tracking it: https://github.com/select2/select2/issues/2879

Right now it can be done through custom renderers, but documentation on those is... lacking. So that may end up being the example renderer when (more developer friendly) documentation is created for them.

**Comment by cyberbit** [comment]
+1 Awesome to see work on this. Can't wait to see that shiny new theme renderer working!

**Comment by ryanbeymer** [comment]
@fk were you able to whip something up? 
If not, I'll start knocking out something with the new classes and identifying the areas that need attention and potential changes from @kevin-brown if possible.

**Comment by fk** [comment]
@kevin-brown @ryanbeymer @cyberbit et al – sorry for not coming back earlier like I promised.
I'll publish a link to a new repository containing my first (fairly complete) shot later tonight.

**Comment by fk** [comment]
I just pushed my work to [a new repository](https://github.com/fk/select2-bootstrap-theme) to avoid handling another version in here.
Demos are up at http://fk.github.io/select2-bootstrap-theme/.

Let me close for tonight by stating that I'm not happy at all with releasing this into the public in its current state – but you waited long enough, right? While I could manage to get rid of some of the Sass verboseness, there are a lot of things that make my stomach hurt:

 * inline documentation sucks/might be confusing or plain wrong
 * the Less version is completely missing – tests will fail
 * RTL support is almost non-existant
 * a demo for nested options is missing
 * I did only test in latest Chrome for now
 * demo pages might be confusing
 * multi-select jumps 1px when dropdown is displayed above

… I guess I'll keep on fixing things during the next few days. ;-)

**Comment by ryanbeymer** [comment]
Thanks... I'll start poking around

**Comment by Soullivaneuh** [comment]
@fk loving it, thanks! :+1:

**Comment by cyberbit** [comment]
@fk Looking great so far!

**Comment by ryanbeymer** [comment]
@fk of the issues that exist still, can you start them over at https://github.com/fk/select2-bootstrap-theme

**Comment by tonytonyjan** [comment]
+1

**Comment by legshooter** [comment]
:+1:

**Comment by almogdesign** [comment]
When is v4.0 support coming out?

**Comment by fk** [comment]
A version of the theme for Select2 v4 is up at http://fk.github.io/select2-bootstrap-theme/ and there's [demos](http://fk.github.io/select2-bootstrap-theme/), too.

While most of the things I mentioned [above](https://github.com/t0m/select2-bootstrap-css/issues/63#issuecomment-88724036) should be fixed, some stuff is still a bit rough, plus I didn't manage to get around to test across browsers yet.

**Comment by stringsonfire** [comment]
Could the above link be added to the Readme for previous versions? Otherwise it's not obvious it exists!

**Comment by flip111** [comment]
bootstrap 4 is coming http://blog.getbootstrap.com/2015/08/19/bootstrap-4-alpha/ anyone knows if that will bring changes in regards to the select2-bootstrap-css ?

**Comment by icfantv** [comment]
@flip111, please don't pollute issues/threads with unrelated questions.  please file a new issue if you want to know about BS4 support.

**Comment by t0m** [comment]
For future reference, @fk put in a ton of work on bugfixes and compatibility with the later versions of bootstrap and was able to get the code merged in as an official theme for bootstrap here: 

https://github.com/select2/select2-bootstrap-theme

So any new issues or feature requests should go there. Some people (like me) may still have a few projects on old versions of bootstrap that still depend upon the original code here so I'll keep the repo up, but I'm going to close out the rest of the tickets regarding new development.

Thanks!
